
export const GET_COLLECTIONS_SUCCESS = 'GET_COLLECTIONS_SUCCESS';
export const GET_COLLECTIONS_FAILURE = 'GET_COLLECTIONS_FAILURE';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE';
export const GET_SINGLE_COLLECTION_SUCCESS = 'GET_SINGLE_COLLECTION_SUCCESS';
export const GET_SINGLE_COLLECTION_FAILURE = 'GET_SINGLE_COLLECTION_FAILURE';

export const ADD_COLLECTION_SUCCESS = 'ADD_COLLECTION_SUCCESS';
export const ADD_COLLECTION_FAILURE = 'ADD_COLLECTION_FAILURE';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';
export const PUT_BOOK_SUCCESS = 'PUT_BOOK_SUCCESS';
export const PUT_BOOK_FAILURE = 'PUT_BOOK_FAILURE';
export const PUT_COLLECTION_SUCCESS = 'PUT_COLLECTION_SUCCESS';
export const PUT_COLLECTION_FAILURE = 'PUT_COLLECTION_FAILURE';
export const ADD_BOOK_TO_COLLECTION_SUCCESS = 'ADD_BOOK_TO_COLLECTION_SUCCESS';
export const ADD_BOOK_TO_COLLECTION_FAILURE = 'ADD_BOOK_TO_COLLECTION_FAILURE';
export const REMOVE_BOOK_FROM_COLLECTION_FAILURE = 'REMOVE_BOOK_FROM_COLLECTION_FAILURE';
export const REMOVE_BOOK_FROM_COLLECTION_SUCCESS = 'REMOVE_BOOK_FROM_COLLECTION_SUCCESS';

export const SET_RATING = 'SET_RATING';
export const PUT_FLAG_COLLECTION = 'PUT_FLAG_COLLECTION';
export const PUT_FLAG_BOOK = 'PUT_FLAG_BOOK';
